Create draft card for Opportunity.
secultce/mapaculturaldesign pull request #20
Opened 2024-08-12 23:32 UTC by saracamilo

##Description:

Creating a draft card for an opportunity

![image](https://github.com/user-attachments/assets/fd4d72bf-a7d0-4cd4-ba8b-adb89f7a7cb4)

## Motivation & Context
## Type of changes

- [ ]  Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

## Checklist

- [ ] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [ ] My code follows the code style of the project (using npm run lint)
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

##Related issues
Fix #8

2024-08-13 13:30 UTC, alessandrofeitoza requested changes

2024-08-13 13:30 UTC, alessandrofeitoza commented on site/static/docs/5.3/css/custom.css
> +  font-family: "Open Sans", sans-serif;
cria uma variavel pra essa fonte, a @Akellymourab tá fazendo algo assim tbm, então pra evitar duplicidade já vê com ela como vai ser feito

2024-08-13 13:30 UTC, alessandrofeitoza commented on site/static/docs/5.3/css/custom.css
> +  color: #000000;
usa uma variavel pra essa cor

2024-08-13 13:30 UTC, alessandrofeitoza commented on site/static/docs/5.3/css/custom.css
> +  background-color: #00A7A7;
todos esses lugares onde tu usa a cor diretamente, seria uma boa criar uma variavel, pq se a gente precisar mudar só muda a variavel

2024-08-14 20:49 UTC, Akellymourab approved these changes

2024-08-15 19:35 UTC, alessandrofeitoza approved these changes

2024-08-15 19:49 UTC, merged